version: '3.8'
# Deploy MongoDB instances

services: 
  my-mongodb: 
    image: mongo
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - mongo_net

  # One-time running service to add sample data
  load-db:
    image: mongo
    depends_on:
      - my-mongodb
    restart: "no"
    volumes:
      - ./database/ecommerce:/ecommerce
    entrypoint: ["mongorestore", "mongodb://root:root@my-mongodb:27017/ecommerce?ssl=false&authSource=admin", "./ecommerce"]
    networks:
      - mongo_net

  # Mongo admin interface
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@my-mongodb:27017/
    networks:
      - mongo_net
    depends_on:
      - my-mongodb

networks:
  mongo_net:
    driver: bridge
